# Generated by Django 4.2 on 2024-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
