# Generated by Django 4.2 on 2024-01-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_capturedimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapturedImage',
        ),
    ]
