# Generated by Django 4.2 on 2024-01-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_imagemodel_alter_face_name_remove_face_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='picture',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AddField(
            model_name='face',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='known_faces/'),
        ),
    ]
