# Generated by Django 4.2 on 2024-01-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_face_picture_delete_imagemodel_face_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
